# Generated by Django 4.2.28 on 2026-02-15 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_original_avatar_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_url',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='original_avatar_url',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='avatars/'),
        ),
    ]
