# Generated by Django 4.2.28 on 2026-02-15 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_avatar_url_alter_user_original_avatar_url'),
    ]

    operations = [
    ]
