# Generated by Django 4.2.28 on 2026-02-15 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_clear_avatar_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='custom_avatar_url',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='avatars/'),
        ),
    ]
