# Generated by Django

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_user_custom_avatar_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='original_avatar_url',
            new_name='intra_avatar_url',
        ),
    ]
