# Generated by Django 4.2.27 on 2026-01-25 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('forfeited', 'Forfeited')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['winner'], name='games_winner__1c1adc_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['started_at'], name='games_started_52471d_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['player_1', 'ended_at'], name='games_player__63d8f2_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['player_2', 'ended_at'], name='games_player__148c22_idx'),
        ),
    ]
