# Generated by Django 4.2.28 on 2026-02-15 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_game_status_game_games_winner__1c1adc_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('forfeited', 'Forfeited')], default='completed', max_length=20),
        ),
    ]
