# Generated by Django 4.2.27 on 2026-01-25 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='friendship',
            index=models.Index(fields=['addressee', 'status'], name='friendships_address_4da91f_idx'),
        ),
        migrations.AddIndex(
            model_name='friendship',
            index=models.Index(fields=['requester', 'status'], name='friendships_request_74cfa7_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_read'], name='notificatio_is_read_3f8c44_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['expires_at'], name='notificatio_expires_66996e_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='notificatio_user_id_a4dd5c_idx'),
        ),
    ]
